#clear && docker build -t show_some_shit_base -f Dockerfile_base .
FROM node:10.16.0

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install
RUN npm i react-scripts

# COPY src src
# COPY public public

# COPY yarn.lock yarn.lock
